server:
  port: 8080
spring:
  application:
    name: evox
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/evox"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
